#!/bin/bash

# Update version.ts with values from package.json
# Used in prebuild step to ensure version consistency

set -e  # Exit on any error

# Get the directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Read package.json and extract version and name
PACKAGE_JSON="$PROJECT_ROOT/package.json"

if [[ ! -f "$PACKAGE_JSON" ]]; then
    echo "Error: package.json not found at $PACKAGE_JSON" >&2
    exit 1
fi

# Extract version and name using jq (more reliable) or fallback to grep/sed
if command -v jq >/dev/null 2>&1; then
    VERSION=$(jq -r '.version' "$PACKAGE_JSON")
    NAME=$(jq -r '.name' "$PACKAGE_JSON")
else
    # Fallback to grep/sed if jq is not available
    VERSION=$(grep '"version"' "$PACKAGE_JSON" | sed 's/.*"version":[[:space:]]*"\([^"]*\)".*/\1/')
    NAME=$(grep '"name"' "$PACKAGE_JSON" | sed 's/.*"name":[[:space:]]*"\([^"]*\)".*/\1/')
fi

# Validate extracted values
if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
    echo "Error: Could not extract version from package.json" >&2
    exit 1
fi

if [[ -z "$NAME" || "$NAME" == "null" ]]; then
    echo "Error: Could not extract name from package.json" >&2
    exit 1
fi

# Generate build time in ISO format
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")

APP_NAME="$NAME"

# Build the version.ts content
VERSION_TS_PATH="$PROJECT_ROOT/src/version.ts"

cat > "$VERSION_TS_PATH" << EOF
/**
 * Build version constants
 * This file is automatically generated during build process
 */
export const BUILD_INFO = {
  version: "$VERSION",
  buildTime: "$BUILD_TIME",
  name: "$NAME",
} as const;

export const APP_VERSION = BUILD_INFO.version;
export const BUILD_TIME = BUILD_INFO.buildTime;
export const APP_NAME = BUILD_INFO.name.includes("/")
  ? BUILD_INFO.name.split("/")[1]
  : BUILD_INFO.name;
EOF

echo "Updated version.ts with version: $VERSION, name: $NAME"
