/**
 * Build version constants
 * This file is automatically generated during build process
 */
export const BUILD_INFO = {
  version: "0.1.2",
  buildTime: "2025-07-07T13:14:55.854Z",
  name: "@unoperate/golem-vaddr-cli",
} as const;

export const APP_VERSION = BUILD_INFO.version;
export const BUILD_TIME = BUILD_INFO.buildTime;
export const APP_NAME = BUILD_INFO.name.includes("/")
  ? BUILD_INFO.name.split("/")[1]
  : BUILD_INFO.name;
